# Generated by Django 4.0.3 on 2023-04-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_field', models.CharField(choices=[('main_entrance', 'main_entrance'), ('open_auditorium', 'open_auditorium'), ('open_gymnasium', 'open_gymnasium'), ('open_tenniscourt', 'open_tenniscourt'), ('open_volleycourt', 'open_volleycourt'), ('apj_park', 'apj_park'), ('parking_front', 'parking_front'), ('squash_court', 'squash_court'), ('parking_back', 'parking_back'), ('badminton_court', 'badminton_court'), ('basketball_court', 'basketball_court'), ('backgate', 'backgate'), ('library', 'library'), ('canteen', 'canteen'), ('stores', 'stores'), ('workshop_block', 'workshop_block'), ('college_ground', 'college_ground'), ('prayer_hall', 'prayer_hall'), ('auditorium', 'auditorium'), ('arch_block', 'arch_block'), ('ladies_washroom', 'ladies_washroom'), ('gents_washroom', 'gents_washroom'), ('coffee_corner', 'coffee_corner'), ('mech_block', 'mech_block'), ('chem_block', 'chem_block'), ('annex_hostel', 'annex_hostel'), ('kilivathil', 'kilivathil')], max_length=100)),
                ('to_field', models.CharField(choices=[('main_entrance', 'main_entrance'), ('open_auditorium', 'open_auditorium'), ('open_gymnasium', 'open_gymnasium'), ('open_tenniscourt', 'open_tenniscourt'), ('open_volleycourt', 'open_volleycourt'), ('apj_park', 'apj_park'), ('parking_front', 'parking_front'), ('squash_court', 'squash_court'), ('parking_back', 'parking_back'), ('badminton_court', 'badminton_court'), ('basketball_court', 'basketball_court'), ('backgate', 'backgate'), ('library', 'library'), ('canteen', 'canteen'), ('stores', 'stores'), ('workshop_block', 'workshop_block'), ('college_ground', 'college_ground'), ('prayer_hall', 'prayer_hall'), ('auditorium', 'auditorium'), ('arch_block', 'arch_block'), ('ladies_washroom', 'ladies_washroom'), ('gents_washroom', 'gents_washroom'), ('coffee_corner', 'coffee_corner'), ('mech_block', 'mech_block'), ('chem_block', 'chem_block'), ('annex_hostel', 'annex_hostel'), ('kilivathil', 'kilivathil')], max_length=100)),
                ('image', models.ImageField(upload_to='static/inmapapi/temp_images')),
                ('distance', models.FloatField()),
            ],
        ),
    ]
