# Generated by Django 4.0.3 on 2023-02-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmapapp', '0002_alter_mymodel_from_alter_mymodel_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='From',
            field=models.CharField(choices=[('open_auditorium', 'open_auditorium'), ('college_gym', 'college_gym'), ('squash_corner', 'squash_corner'), ('apj_park', 'apj_park'), ('main_gate', 'main_gate'), ('main_entrance', 'main_entrance'), ('central_portico', 'central_portico'), ('machines_lab', 'machines_lab'), ('ladies_toilet', 'ladies_toilet'), ('arch_block', 'arch_block'), ('auditorium', 'auditorium'), ('basketball_court', 'basketball_court'), ('parking_gate', 'parking_gate'), ('library', 'library'), ('mech_workshop', 'mech_workshop'), ('campus_doctor', 'campus_doctor'), ('cooperative_store', 'cooperative_store'), ('canteen', 'canteen'), ('college_ground', 'college_ground'), ('electrical_lab', 'electrical_lab'), ('mech_block', 'mech_block'), ('chem_block', 'chem_block'), ('coffee_corner', 'coffee_corner'), ('kilivathil', 'kilivathil'), ('annex_hostel', 'annex_hostel')], default='Hall', max_length=600),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='To',
            field=models.CharField(choices=[('open_auditorium', 'open_auditorium'), ('college_gym', 'college_gym'), ('squash_corner', 'squash_corner'), ('apj_park', 'apj_park'), ('main_gate', 'main_gate'), ('main_entrance', 'main_entrance'), ('central_portico', 'central_portico'), ('machines_lab', 'machines_lab'), ('ladies_toilet', 'ladies_toilet'), ('arch_block', 'arch_block'), ('auditorium', 'auditorium'), ('basketball_court', 'basketball_court'), ('parking_gate', 'parking_gate'), ('library', 'library'), ('mech_workshop', 'mech_workshop'), ('campus_doctor', 'campus_doctor'), ('cooperative_store', 'cooperative_store'), ('canteen', 'canteen'), ('college_ground', 'college_ground'), ('electrical_lab', 'electrical_lab'), ('mech_block', 'mech_block'), ('chem_block', 'chem_block'), ('coffee_corner', 'coffee_corner'), ('kilivathil', 'kilivathil'), ('annex_hostel', 'annex_hostel')], default='Hall', max_length=600),
        ),
    ]
