# Generated by Django 4.0.3 on 2023-04-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('api_cred', models.CharField(max_length=255, unique=True)),
                ('api_secret', models.CharField(max_length=255, unique=True)),
                ('expected_requests', models.PositiveIntegerField(default=0)),
                ('last_used_time', models.DateTimeField(auto_now=True)),
                ('total_usage', models.PositiveIntegerField(default=0)),
                ('usage_per_day', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
