# Generated by Django 4.0.3 on 2023-04-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmap_cred', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiaccounts',
            old_name='organisation',
            new_name='organization',
        ),
    ]
